### ISSUE TITLE
[TODO] 검색 시 카드에 장소 주소 출력

### ISSUE THREAD

**Issue by sanmong** [sanmong/SKKU_Trip_Checker#29]
## 📌  요약

- 기존에 단순 html에서 주소를 출력하였으나

- 검색에 맞게 동적으로 카드를 출력하며 주소를 poiId로 대체해 놓았습니다.

## 📔  상세

검색 시 카드 출력에 사용하는 API와 exhibitList에 주소(현실)이 없어
현재contents.poiId로 대체해 놓았습니다.

poiId를 통해 검색하는 기능을 구현할 까 하였으나 
현재 주소가 있는 data.js에서 for문으로 검색하기엔 너무 오래 걸려 
일단 poiId를 주소 대신 출력하게 해놓았습니다.

**Comment by olenmg** [comment]
#31 에서 주소를 정보 리스트에 함께 넘겨주는 방식으로 해결하였습니다.
