### ISSUE TITLE
[QA] Card generation 코드 함수화

### ISSUE THREAD

**Issue by sanmong** [sanmong/SKKU_Trip_Checker#32]
##  📸  코드

- 코드나 코드에 대한 스크린샷을 첨부해주세요.
![code1](https://user-images.githubusercontent.com/83284563/205076151-5a524899-24a3-406a-b202-560eb84a1dea.png)
![code2](https://user-images.githubusercontent.com/83284563/205076168-12d73a5b-7af0-4d96-9a6a-a68af06718d0.png)

---

현재 다른 여러 방법을 사용해보았으나 본래 버튼 이벤트로 있던 코드를 함수화시키는 것외의 방법은 성공하지 못했습니다.
일단 아래에 있던 코드를 함수화시키면 메인과 검색모두 작동은 합니다

**Comment by olenmg** [comment]
Reference를 통해 #35 에서 해결되었습니다.
Reference: [Link](https://junilhwang.github.io/TIL/Javascript/Design/Vanilla-JS-Component/#_1-%E1%84%80%E1%85%B5%E1%84%82%E1%85%B3%E1%86%BC-%E1%84%8E%E1%85%AE%E1%84%80%E1%85%A1)
